// R8 designer brief (#198): pure view-model helpers for BriefPage.
//
// No React and no runtime api import (api.ts only as `import type` — the
// compiled module must stay importable under Node, same ritual as copy.ts /
// sceneVariants.ts). Covers the four testable concerns of the brief page:
//
//   1. the privacy checklist (default checkbox states + inclusion filtering,
//      unchecked images are removed from the preview/print DOM),
//   2. furniture-intent grouping with id-free display labels,
//   3. section presence (a missing wire section never renders an empty
//      header),
//   4. the notes autosave persister (single debounced PATCH per quiet period)
//      and the print trigger (injectable stub in tests).
//
// Visible labels NEVER contain raw ids (#188 glossary rule): entity names
// fall back to the kind label, rooms to «Помещение», photos to «Фото N».

import type {
  BriefDocument,
  BriefFurnitureEntity,
  BriefFurnitureIntents,
  BriefNotes,
  BriefPhoto,
  BriefRoom
} from "./api";
import {
  BRIEF_CONCEPT_NOT_PHOTO,
  BRIEF_INTENT_GROUP_ORDER,
  briefIntentGroupLabel,
  briefScaleLabel,
  entityKindLabel,
  mappingConfidenceLabel,
  renderStageLabel
  // ".js" specifier: the ritual-compiled build/briefView.js must load under
  // Node ESM (same convention as sceneVariants.ts → twinDesign.js).
} from "./copy.js";

// ---------------------------------------------------------------------------
// Privacy checklist (#198): every image the brief could carry, with its
// default inclusion state. Renders are checked (generated by this project),
// photos and style references start unchecked (privacy default).
// ---------------------------------------------------------------------------

export type BriefImageKind = "render" | "photo" | "reference";

export type BriefImageItem = {
  /** Stable checkbox key (UI-internal, never rendered). */
  key: string;
  kind: BriefImageKind;
  assetId: string;
  /** Human label without raw ids (#188). */
  label: string;
  checked: boolean;
};

/** Checkbox key shared by collectBriefImages / section presence. */
export function briefImageKey(
  kind: BriefImageKind,
  index: number,
  assetId: string
): string {
  return `${kind}:${index}:${assetId}`;
}

/** Photo caption: owner-entered caption (BE: asset original name) or a
 * numbered fallback — never the attachment/asset id. */
export function briefPhotoLabel(
  caption: string | null | undefined,
  index: number
): string {
  const text = typeof caption === "string" ? caption.trim() : "";
  return text || `Фото ${index + 1}`;
}

/**
 * Default checkbox states (order: renders, photos, style references; wire
 * order preserved inside each group). Items without an asset id are skipped —
 * there is nothing to show a designer.
 */
export function collectBriefImages(brief: BriefDocument): BriefImageItem[] {
  const items: BriefImageItem[] = [];
  brief.renders?.forEach((render, index) => {
    if (!render.asset_id) return;
    items.push({
      key: briefImageKey("render", index, render.asset_id),
      kind: "render",
      assetId: render.asset_id,
      label: `Рендер ${index + 1} · ${renderStageLabel(render.stage)}`,
      checked: true
    });
  });
  brief.photos?.forEach((photo, index) => {
    if (!photo.asset_id) return;
    items.push({
      key: briefImageKey("photo", index, photo.asset_id),
      kind: "photo",
      assetId: photo.asset_id,
      label: briefPhotoLabel(photo.caption, index),
      checked: false
    });
  });
  brief.style_direction?.reference_asset_ids?.forEach((assetId, index) => {
    if (!assetId) return;
    items.push({
      key: briefImageKey("reference", index, assetId),
      kind: "reference",
      assetId,
      label: `Референс стиля ${index + 1}`,
      checked: false
    });
  });
  return items;
}

/** Only checked images reach the preview and the printout (DOM removal). */
export function filterIncludedImages(
  items: readonly BriefImageItem[]
): BriefImageItem[] {
  return items.filter((item) => item.checked);
}

// ---------------------------------------------------------------------------
// Rooms + furniture intents: id-free display labels (#188), room names
// resolved from the rooms list, empty groups omitted entirely.
// ---------------------------------------------------------------------------

/** Room display name: BE name or the neutral fallback — never the room id. */
export function briefRoomLabel(room: {
  name?: string | null;
}): string {
  const name = typeof room.name === "string" ? room.name.trim() : "";
  return name || "Помещение";
}

/** Entity display name: BE name or the kind glossary label — never the id. */
export function briefEntityLabel(entity: {
  kind: string;
  name?: string | null;
}): string {
  const name = typeof entity.name === "string" ? entity.name.trim() : "";
  return name || entityKindLabel(entity.kind);
}

export type BriefIntentGroup = {
  key: (typeof BRIEF_INTENT_GROUP_ORDER)[number];
  label: string;
  entities: { id: string; label: string; roomLabel: string | null }[];
};

/**
 * Group furniture intents for the brief (fixed order Сохранить/Убрать/
 * Заменить/Закреплено). Empty groups disappear (BE already omits them; the
 * UI re-checks because checkbox state never creates sections). The «locked»
 * group may overlap keep/remove/replace — BE emits the entity in both.
 */
export function groupIntentEntities(
  intents: BriefFurnitureIntents | null | undefined,
  rooms: readonly BriefRoom[] | null | undefined
): BriefIntentGroup[] {
  if (!intents) return [];
  const roomNames = new Map(
    (rooms ?? []).map((room) => [room.id, briefRoomLabel(room)])
  );
  const groups: BriefIntentGroup[] = [];
  for (const key of BRIEF_INTENT_GROUP_ORDER) {
    const members = intents[key];
    if (!members || members.length === 0) continue;
    groups.push({
      key,
      label: briefIntentGroupLabel(key),
      entities: members.map((entity) => ({
        id: entity.id,
        label: briefEntityLabel(entity),
        roomLabel: entity.room_id ? roomNames.get(entity.room_id) ?? null : null
      }))
    });
  }
  return groups;
}

// ---------------------------------------------------------------------------
// Preview sections: only present wire sections render — never an empty
// header (#198). Image sections additionally require at least one INCLUDED
// image (unchecked images are removed from the preview/print DOM).
// ---------------------------------------------------------------------------

export type BriefSectionId =
  | "notes"
  | "plan"
  | "rooms"
  | "furniture"
  | "renders"
  | "photos"
  | "style"
  | "budget"
  | "questions";

export type BriefSectionInput = {
  brief: BriefDocument;
  /** Keys of the currently checked images (from filterIncludedImages). */
  includedKeys: ReadonlySet<string>;
  /** Live composer state (needs/wishes text non-empty). */
  hasNeedsWishes: boolean;
  /** Live composer state (questions text non-empty). */
  hasQuestions: boolean;
};

export function briefSectionIds(input: BriefSectionInput): BriefSectionId[] {
  const { brief, includedKeys, hasNeedsWishes, hasQuestions } = input;
  const sections: BriefSectionId[] = [];
  if (hasNeedsWishes) sections.push("notes");
  if (brief.plan) sections.push("plan");
  if ((brief.rooms?.length ?? 0) > 0) sections.push("rooms");
  if (groupIntentEntities(brief.furniture_intents, brief.rooms).length > 0) {
    sections.push("furniture");
  }
  const hasIncluded = (kind: BriefImageKind): boolean => {
    const source =
      kind === "render"
        ? brief.renders
        : kind === "photo"
          ? brief.photos
          : brief.style_direction?.reference_asset_ids;
    return (
      (source?.some((item, index) => {
        // Renders/photos carry {asset_id} objects; style references are
        // plain asset-id strings (BE wire, #198) — normalize to the id.
        const assetId =
          typeof item === "string"
            ? item
            : typeof (item as { asset_id?: unknown })?.asset_id === "string"
              ? (item as { asset_id: string }).asset_id
              : null;
        return assetId
          ? includedKeys.has(briefImageKey(kind, index, assetId))
          : false;
      }) ?? false)
    );
  };
  if (hasIncluded("render")) sections.push("renders");
  if (hasIncluded("photo")) sections.push("photos");
  const style = brief.style_direction;
  if (
    style &&
    ((style.source_text?.trim() ?? "") !== "" ||
      hasIncluded("reference"))
  ) {
    sections.push("style");
  }
  const budget = brief.budget;
  if (
    budget &&
    ((budget.items?.length ?? 0) > 0 || (budget.disclaimer?.trim() ?? "") !== "")
  ) {
    sections.push("budget");
  }
  if (hasQuestions) sections.push("questions");
  return sections;
}

/** «Масштаб: …» line for the plan section; null when there is no plan block. */
export function briefScaleLine(brief: BriefDocument): string | null {
  if (!brief.plan) return null;
  const label = briefScaleLabel(brief.plan.scale);
  const mm = brief.plan.scale?.mm_per_px;
  const mmText =
    typeof mm === "number" && Number.isFinite(mm) && mm > 0
      ? ` · ${mm} мм на пиксель`
      : "";
  return `Масштаб: ${label}${mmText}`;
}

/** Provenance line under the header: short head-revision hash (8 chars). */
export function briefShortHash(
  hash: string | null | undefined
): string | null {
  if (!hash) return null;
  return hash.length > 8 ? hash.slice(0, 8) : hash;
}

/** Render card disclaimer: BE label («Концепт, не фотография») or the fixed
 * fallback when a future BE sends an empty label. */
export function briefRenderDisclaimer(label: string | null | undefined): string {
  const text = typeof label === "string" ? label.trim() : "";
  return text || BRIEF_CONCEPT_NOT_PHOTO;
}

/** Photo mapping note: R7 confidence label when the mapping carries one. */
export function briefPhotoMappingNote(
  mapping: Record<string, unknown> | null | undefined
): string | null {
  const confidence = mapping?.confidence;
  return typeof confidence === "string"
    ? mappingConfidenceLabel(confidence)
    : null;
}

// ---------------------------------------------------------------------------
// Notes persister: quiet-period debounce → one PATCH per burst (PlanEditor
// autosave pattern). patch() receives the latest notes; edits made while a
// PATCH is in flight queue exactly one follow-up call.
// ---------------------------------------------------------------------------

export type NotesPersister = {
  schedule: (next: BriefNotes) => void;
  /**
   * Drain all outstanding notes edits and resolve only when nothing is
   * pending AND no PATCH is in flight (used on blur and on unmount). Edits
   * typed while a PATCH is in flight are delivered — never silently dropped
   * (M1: a single run() used to no-op past an in-flight PATCH, so the queued
   * follow-up was lost the moment dispose() cleared it).
   */
  flush: () => Promise<void>;
  /**
   * Stop the debounce timer. While a PATCH is in flight, queued edits stay
   * queued — the in-flight chain delivers them; with no PATCH in flight the
   * pending edit is dropped (nothing would ever trigger it).
   */
  dispose: () => void;
};

export function createNotesPersister(input: {
  patch: (notes: BriefNotes) => Promise<unknown>;
  /** Quiet-period length in ms (BriefPage uses 800). */
  debounceMs?: number;
}): NotesPersister {
  const debounceMs = input.debounceMs ?? 800;
  let timer: ReturnType<typeof setTimeout> | null = null;
  let pending: BriefNotes | null = null;
  // The in-flight PATCH promise (null = idle). A promise handle rather than a
  // bare flag: flush() must be able to WAIT it out, not step over it.
  let current: Promise<void> | null = null;

  async function run(): Promise<void> {
    if (current !== null || pending === null) return;
    const value = pending;
    pending = null;
    current = (async () => {
      try {
        await input.patch(value);
      } finally {
        current = null;
      }
    })();
    await current;
    // Edits made during the PATCH: exactly one follow-up with the latest value.
    if (pending !== null) void run().catch(() => undefined);
  }

  return {
    schedule(next: BriefNotes) {
      pending = next;
      if (timer !== null) clearTimeout(timer);
      timer = setTimeout(() => {
        timer = null;
        void run().catch(() => undefined);
      }, debounceMs);
    },
    async flush() {
      if (timer !== null) {
        clearTimeout(timer);
        timer = null;
      }
      // Drain: wait out any in-flight PATCH, then deliver whatever was queued
      // behind it; repeat until both are settled.
      while (pending !== null || current !== null) {
        if (current !== null) {
          await current;
        } else {
          await run();
        }
      }
    },
    dispose() {
      if (timer !== null) clearTimeout(timer);
      timer = null;
      // An in-flight chain still delivers queued edits (M1) — only drop a
      // pending edit when nothing can ever deliver it.
      if (current === null) pending = null;
    }
  };
}

// ---------------------------------------------------------------------------
// Print: «Скачать PDF» → the browser's print dialog over the print stylesheet.
// Kept in this pure module so tests can stub globalThis.window (#198).
// ---------------------------------------------------------------------------

export function downloadBriefPdf(): void {
  window.print();
}
